variables:
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .venv

stages:
  - build

build:
  image: matanrubin/python-poetry:3.7
  stage: build
  script:
    - poetry config settings.virtualenvs.in-project true
    - make bootstrap
    - make package
    - poetry install --extras flask --extras fastapi
    - make check
    - make coverage
    - poetry install --extras psutil
    - make test
  artifacts:
    paths:
      - htmlcov
