[tool.poetry]
name = "pyctuator"
version = "0.1.0"
description = "A Python implementation of the Spring Actuator API for popular web frameworks"
authors = [
    "Michael Yakobi <michael.yakobi@solaredge.com>",
    "Inbal Levi <inbal.levi@solaredge.com>",
    "Yanay Reingewertz <yanay.reingewertz@solaredge.com>",
    "Matan Rubin <matan.rubin@solaredge.com>"
]

[tool.poetry.dependencies]
python = "^3.7"
psutil = { version = "^5.6", optional = true }
flask = { version = "^1.1", optional = true }
fastapi = { version = "^0.41.0", optional = true }
uvicorn = { version = "^0.9.0", optional = true }
sqlalchemy = {version = "^1.3", optional = true}
PyMySQL = {version = "^0.9.3", optional = true}
cryptography = {version = "^2.8", optional = true}
redis = {version = "^3.3", optional = true}

[tool.poetry.dev-dependencies]
requests = "^2.22"
pytest = "^3.0"
mypy = "^0.730.0"
pylint = "^2.4"
pytest-cov = "^2.8"
autopep8 = "^1.4"

[tool.poetry.extras]
psutil = ["psutil"]
fastapi = ["fastapi", "uvicorn"]
flask = ["flask"]
db = ["sqlalchemy", "PyMySQL", "cryptography"]
redis = ["redis"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
